// ESBuild 横幅插件
// 在打包文件顶部添加版权信息和构建信息

export function bannerPlugin(options = {}) {
  return {
    name: 'banner-plugin',
    setup(build) {
      const {
        banner = '// Generated by ESBuild',
        includeTimestamp = true,
        includeVersion = true,
        author = 'ESBuild Learning Project',
        license = 'MIT'
      } = options;
      
      build.onEnd((result) => {
        console.log('🎯 横幅插件：构建完成，添加横幅信息');
        
        // 在这里可以添加后处理逻辑
        // 例如文件处理、统计信息等
      });
      
      // 设置构建选项中的横幅
      build.initialOptions.banner = build.initialOptions.banner || {};
      build.initialOptions.banner.js = createBanner({
        banner,
        includeTimestamp,
        includeVersion,
        author,
        license
      });
    }
  };
}

function createBanner({ banner, includeTimestamp, includeVersion, author, license }) {
  const lines = [
    banner,
    `// Author: ${author}`,
    `// License: ${license}`
  ];
  
  if (includeTimestamp) {
    lines.push(`// Build Time: ${new Date().toISOString()}`);
  }
  
  if (includeVersion) {
    lines.push(`// ESBuild Version: ${process.env.npm_package_version || '1.0.0'}`);
  }
  
  lines.push('//');
  
  return lines.join('\n');
}
